blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'), # Django spodziewa się liczby całkowitej i przekaże jej wartość do widoku jako zmienną pk
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

bookstore/urls.py
from django.urls import path
from . import views

app_name = "bookstore"

urlpatterns = [
    path('customer/new/', views.create_customer, name='create_customer'),
    path('customer/new/added', views.customer_added_successfully, name='customer_added_successfully'),
    path('customer/all/', views.all_customers, name='all_customers'),
    path('customer/all/<int:id>', views.show_bought_books_by_selected_customer, name='show_bought_books_by_selected_customer'),
    path('customer/order/', views.show_books_to_order, name='show_books_to_order'),
    path('customer/order/<int:id>', views.select_buyer, name='select_buyer'), # Django spodziewa się liczby całkowitej i przekaże jej wartość do widoku jako zmienną id
    path('book/new/', views.create_book, name='create_book'),
    path('book/new/added/', views.book_added_successfully, name='book_added_successfully'),
    path('book/all/', views.all_books, name='all_books'),
    path('', views.bookstore_home_page, name='bookstore_home_page'),
]

iss/urls.py
from django.urls import path
from . import views

app_name = "iss"

urlpatterns = [
    path('', views.iss_home_page_method, name='iss_home_page'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),  # blog from djagogirls
    path('bookstore/', include('bookstore.urls')),  # my bookstore
    path('polls/', include('polls.urls')),  # polls from docs.djangoproject.com
    # path('wholesale/', include('wholesale.urls')),  # my wholesale
    # path('search/', include('search.urls')),  # my search
    path('findword/', include('findword.urls')),  # my findword
    # path('todolist/', include('todolist.urls')),  # my todolist
    path('todo/', include('todo.urls')),  # my
    path('iss/', include('iss.urls')),  # my iss
    path('ip/', include('ipcalculator.urls')),  # my ipcalculator
]

polls/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    # old urls
    # # ex: /polls/
    # path('', views.index, name='index'),
    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from django.shortcuts import render, get_object_or_404
from .forms import PostForm


# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

blog/templates/blog/base.html
<html>
{% load static %}
    <head>
        <title>Kamil's site</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<!--        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">-->
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>

    <body>
        <div class="page-header" style="background-color: #303030;">
            {% if user.is_authenticated %}
                <a href="{% url 'post_new' %}" class="top-menu">Add post <span class="glyphicon glyphicon-plus"> </span></a>
            {% endif %}
            <h1><a style="cursor: pointer;" href="/" >Kamil Bienias - home page.</a></h1>
            <p style="color:white; font-size: 18px;">Projects: &nbsp&nbsp</p>
            <div>
            <a href="{% url 'polls:index' %}" id="polls" onmouseover="polls()" onmouseout="polls_normal()" style="font-size: 18px; text-decoration: none; cursor: pointer">&nbsp&nbsp&nbsp polls</a><br>
            <a href="{% url 'bookstore:bookstore_home_page' %}" id="bookstore" onmouseover="bookstore()" onmouseout="bookstore_normal()" style="font-size: 18px; text-decoration: none; cursor: pointer">&nbsp&nbsp&nbsp bookstore</a><br>
            <a href="findword/" id="searching" onmouseover="searching()" onmouseout="searching_normal()" style="font-size: 18px; text-decoration: none; cursor: pointer">&nbsp&nbsp&nbsp searching</a><br>
            <a href="todo/" id="todolist" onmouseover="todolist()" onmouseout="todolist_normal()" style="font-size: 18px; text-decoration: none; cursor: pointer">&nbsp&nbsp&nbsp ToDoList</a><br>
            <a href="iss/" id="iss" onmouseover="iss()" onmouseout="iss_normal()" style="font-size: 18px; text-decoration: none; cursor: pointer">&nbsp&nbsp&nbsp International Space Station</a><br>
            <a href="ip/" id="ip" onmouseover="ip()" onmouseout="ip_normal()" style="font-size: 18px; text-decoration: none; cursor: pointer">&nbsp&nbsp&nbsp IP calculator</a><br>
            </div>
            <div style="clear:both"></div>
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
    <script>
            function polls()
            {
               document.getElementById('polls').innerHTML="__polls__(self)";
            }

            function polls_normal()
            {
               document.getElementById('polls').innerHTML="&nbsp&nbsp&nbsp polls";
            }

            function bookstore()
            {
               document.getElementById('bookstore').innerHTML="__bookstore__(self)";
            }

            function bookstore_normal()
            {
               document.getElementById('bookstore').innerHTML="&nbsp&nbsp&nbsp bookstore";
            }

            function searching()
            {
               document.getElementById('searching').innerHTML="__searching__(self)";
            }

            function searching_normal()
            {
               document.getElementById('searching').innerHTML="&nbsp&nbsp&nbsp searching";
            }

            function todolist()
            {
               document.getElementById('todolist').innerHTML="__ToDoList__(self)";
            }

            function todolist_normal()
            {
               document.getElementById('todolist').innerHTML="&nbsp&nbsp&nbsp ToDoList";
            }

            function iss()
            {
               document.getElementById('iss').innerHTML="__International Space Station__(self)";
            }

            function iss_normal()
            {
               document.getElementById('iss').innerHTML="&nbsp&nbsp&nbsp International Space Station";
            }

            function ip()
            {
               document.getElementById('ip').innerHTML="__IP calculator__(self)";
            }

            function ip_normal()
            {
               document.getElementById('ip').innerHTML="&nbsp&nbsp&nbsp IP calculator";
            }
    </script>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a> <!-- tylko zalogowani widzą "ołówek" edycji"
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h5 style="color:red">Posty mogą dodawać tylko zalogowani użytkownicy.</h5>
    <h5 style="color:red">Na razie tylko administrator może się logować. Niezalogowani nie widzą na dole przycisku "Zapisz post"</h5>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        {% if user.is_authenticated %}
            <button type="submit" class="save btn btn-default" style="color:green"><b>Zapisz post</b></button>
        {% endif %}
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}